[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.2"
reqwest =  {version ="0.11.14"}
tokio = { version = "1.25.0", features = ["full"] }
whatlang = "0.16.2"
